FanFollow/.swiftlint.yml, FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/AppDelegate.swift, FanFollow/FanFollow/SceneDelegate.swift, FanFollow/FanFollowTests/FanFollowTests.swift
=> config : 프로젝트 lint 파일 추가

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Application/SceneDelegate.swift, FanFollow/FanFollow/Source/NetworkManager/Network.swift, FanFollow/FanFollow/Source/NetworkManager/NetworkError.swift, FanFollow/FanFollow/Source/NetworkManager/NetworkManager.swift, FanFollow/FanFollow/Source/ViewController.swift
네트워크 타입 구현하였습니다.
- 네트워크 타입은 Data타입만 반환하도록 구현함.
- Service 타입들의 역활로 디코딩을 하도록 함.
=> feat : Network 타입 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Resource/SupabaseInfo.plist, FanFollow/FanFollow/Source/Util/Extension/Bundle+Extension.swift
내용
git update-index --skip-worktree FanFollow/FanFollow/Resource/SupabaseInfo.plist
git update-index --no-skip-worktree 다시포함시키고싶은파일명
=> config : Bundle Extension 구현 및 SupabaseInfo.plist  추가하여 Key값 보관

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/ServiceTests/Stub/StubNetworkManager.swift
Service 타입을 테스트하기 위해서 공통적으로 필요한 Stub Network Manager를 구현합니다.
- StubNetworkManager 구현
=> [TEST] StubNetworkManager 타입 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/ServiceTests/ChatServiceTests.swift, FanFollow/ServiceTests/FollowServiceTests.swift, FanFollow/ServiceTests/UserInformationServiceTests.swift
- FollowService, UserInformationService 테스트 작성
- 정상적인 값일 때 확인 / 에러일 때 확인
=> [TEST] FollowService, UserInformationService 테스트 작성

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Data/DefaultPostService.swift, FanFollow/FanFollow/Source/Data/Protocol/PostService.swift, FanFollow/ServiceTests/Mock/Mock.swift, FanFollow/ServiceTests/PostServiceTests.swift
- PostService TestCode 작성
- PostService TestCode 작성 및 PostDTO Extionsion하여 MockData 추가
- PostService 메서드 파라미터 값 부분 수정(이름, 옵셔널 변경)
|Test Coverage|
|:---:|
|![PostService TestCoverage](https://github.com/Young-Child/FanFollow/assets/59204352/b6107f99-4f01-4cba-bc2b-2b0f7be20c08)|
=> [TEST] PostService 테스트 작성 

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/ServiceTests/LikeServiceTests.swift, FanFollow/ServiceTests/Mock/Mock.swift, FanFollow/ServiceTests/PostServiceTests.swift, FanFollow/ServiceTests/UserInformationServiceTests.swift
- LikeService 테스트 코드 작성
- LikeService 테스트 코드 작성
- LikeService Count값 반환에 대한 MockData 추가
|TestCoverage|
|:---:|
|![image](https://github.com/Young-Child/FanFollow/assets/59204352/c478ee77-2fdb-4e5a-a030-34fc091607ad)|
=> [Test] LikeService 테스트 코드 작성

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Data/Model/ChatDTO.swift, FanFollow/FanFollow/Source/Data/Repository/DefaultChatRepository.swift, FanFollow/FanFollow/Source/Domain/Model/ChatRoom.swift, FanFollow/FanFollow/Source/Domain/UseCase/AccessChatRoomUseCase.swift, FanFollow/FanFollow/Source/Domain/UseCase/FetchChatRoomUseCase.swift, FanFollow/FanFollow/Source/Network/Builder/ChatRequestDirector.swift, FanFollow/RepositoryTests/ChatServiceTests.swift
- AccessChatRoomUseCase 구현
- Supabase RPC Function 구현 후, 적용
- AccessChatRoomUseCase 구현
- ChatRoom Entity 구현
- ChatRequestDirector : requestChattingList() 메서드 내부 구현 RPC 적용하여 수정 
- 추후 테스트 진행 예정
- 현재 list불러와서 ChatRoom 배열타입으로 변경, 채팅방 떠나기, 채팅방 삭제 구현해놓았는데,
Create 미구현 이유는 Create같은 경우 피드에서 메세지 보내기 등과 같은 버튼을 눌렀을 때 수행되어야해서 현재는 구현하지 않았습니다.
=> [FEATURE] AccessChatRoomUseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Data/Model/UserInformationDTO.swift, FanFollow/FanFollow/Source/Data/Repository/DefaultUserInformationRepository.swift, FanFollow/FanFollow/Source/Domain/Model/Creator.swift, FanFollow/FanFollow/Source/Domain/Model/Fan.swift, FanFollow/FanFollow/Source/Domain/Model/JobCategory.swift, FanFollow/FanFollow/Source/Domain/Model/User.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift, FanFollow/RepositoryTests/FollowServiceTests.swift, FanFollow/RepositoryTests/UserInformationServiceTests.swift
- User Model 타입 구현과 관련 타입 구현
- DB name Column 삭제 및 코드 내부 name 사용처 삭제 (테스트 코드 적용하였습니다.)
- User 프로토콜 정의
- Creator Model 타입 구현
- Fan Model 타입 구현
- JobCategory enum 구현
- 특이사항 없습니다.
=> [FEATURE] User 타입 구현 및 관련 타입 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Domain/UseCase/ChangeLikeUseCase.swift
- ChangeLikeUseCase 구현
- ChangeLikeUseCase 구현
- checkPostLiked : 포스트 좋아요 여부 확인
- fetchPostLikeCount : 포스트 좋아요 개수 조회
- createPostLike : 좋아요 등록
- deletePostLike : 좋아요 취소
- UseCase 전체 구현 후 테스트 코드 작성
=> [FEATURE] ChangeLikeUseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Domain/Model/Creator.swift, FanFollow/FanFollow/Source/Domain/Model/Fan.swift, FanFollow/FanFollow/Source/Domain/Model/JobCategory.swift, FanFollow/FanFollow/Source/Domain/Model/User.swift, FanFollow/FanFollow/Source/Domain/UseCase/FetchUserInformationUseCase.swift
- FetchUserInformationUseCase 구현
- [Fan 에 init 추가](https://github.com/Young-Child/FanFollow/commit/7a926b2505f9068464521e6b73f1d817db255689)
- [JobCategory 에 Int 타입 원시값 추가](https://github.com/Young-Child/FanFollow/commit/9fd07765805ca514e7e94b296a255b08d9c2fa95)
- [Creator 에 실패가능한 init 추가](https://github.com/Young-Child/FanFollow/commit/dec995cc6219a20a665f5b37412191bb73595fde)
- [FetchUserInformationUseCase 구현](https://github.com/Young-Child/FanFollow/commit/766523f097595720731a26bd7458accb01897695)
- fetchUserInformation : user 정보 조회 (크리에이터면 Creator, 아니면 Fan 타입으로 반환)
- UseCase 전체 구현 후 테스트 코드 작성
=> [FEATURE] FetchUserInformationUseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorPostsUseCase.swift
- FetchCreatorPostsUseCase 구현
- FetchCreatorPostsUseCase 구현
- fetchCreatorPosts : 크리에이터가 작성한 포스트 목록 조회
- UseCase 전체 구현 후 테스트 코드 작성
=> [FEATURE] FetchCreatorPostsUseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/UseCaseTests/AccessChatRoomUseCaseTests.swift, FanFollow/UseCaseTests/Stub/StubChatRepository.swift
- AccessChatRoom Test
- AccessChatRoom Test 코드 작성
- StubChatRepository 구현
|스크린샷|
|:---:|
|<img width="1275" alt="TestCoverage" src="https://github.com/Young-Child/FanFollow/assets/59204352/c578fc5e-9d8d-48f4-90b6-99347451db6a">|
=> [TEST] AccessChatRoomUseCase Test 작성

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Application/SceneDelegate.swift, FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/TopTabBarController.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/SettingTabItem.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/View/TabBar.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/SettingViewModel.swift, FanFollow/FanFollow/Source/Util/Extension/UI/UITableView+Extension.swift
- Setting View Controller에 대응되는 ViewModel 생성
- 사용자 상태에 따른 탭바 변경될 수 있도록 변경
- Setting Tab Bar Controller
- Setting View Controller
|기능|스크린샷|
|:---:|:---:|
|사용자 상태에 따른 탭바 변경 (팬)|<img src = "https://github.com/Young-Child/FanFollow/assets/52390923/f5f5a3ed-e092-4d9f-adb5-bc13abedc3ca" width = "300"/>|
|사용자 상태에 따른 탭바 변경 (크리에이터)|<img src = "https://github.com/Young-Child/FanFollow/assets/52390923/84342e7b-16c0-4a8d-96ef-6712f829f801" width = "300"/>|
- ViewModel 영역에서 데이터 설정하도록 작성하였습니다.
- TabBar 영역과의 데이터를 전달하기 위해서 Delegate 패턴을 활용하였는데, 다른 방법이 있으면 더 좋을 것 같습니다 ㅜ
=> [FEATURE] Setting View Model 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Domain/UseCase/AccessChatRoomUseCase.swift, FanFollow/FanFollow/Source/Domain/UseCase/ExploreUseCase.swift, FanFollow/FanFollow/Source/Domain/UseCase/SearchCreatorUseCase.swift
- SearchCreatorUseCase 구현
- SearchCreatorUseCase에서 검색 결과에 따른 CreatorList 가져오는 메서드 구현
- 테스트 계획 O
- debounce의 사용 위치에 대해 고민을 해봤는데, ViewModel에 있다면 사용할 때마다 debounce를 넣어줘야할 것 같기도 하고, UseCase에서 deboucne를 넣는방향이 검색 기능의 역할을 더 가져가는 것 같고 중복코드 방지할 수 있을 것 같아 해당위치에서 사용하였습니다.
- 나중에 deboucne 시간이나 스레드는 추후 변경될 수 있습니다.
=> [FEATURE] SearchCreatorUseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Resource/Assets.xcassets/CategoryCellColor.colorset/Contents.json, FanFollow/FanFollow/Source/Domain/Model/ExploreSectionItem.swift, FanFollow/FanFollow/Source/Domain/Model/ExploreSectionModel.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/ExploreTabBarController.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/ExploreTapItem.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Protocol/Reusable.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/View/CategoryCell.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/View/CreatorCell.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/View/ExploreCollectionReusableHeaderView.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/View/ExploreViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ViewModel/ExploreViewModel.swift, FanFollow/FanFollow/Source/Presenter/MainScene/View/TabBarController.swift, FanFollow/FanFollow/Source/Util/Extension/UI/UICollectionView+Extension.swift
- ExploreViewController, ExploreViewModel 구현
- ExploreViewController 구현 
- ExploreViewModel 구현
- CreatorCell 구현
- CategoryCell 구현
- ExploreCollectionReusableHeaderView 구현
|기능|스크린샷|
|:---:|:---:|
|Explore|<img width = "300px" img src= "https://github.com/Young-Child/FanFollow/assets/59204352/54a287eb-a477-4839-89a7-f8ea4deca077">|
추후 카테고리 버튼 누른 후, 그 다음 보여지는 화면까지 구성 후에 Test 진행할 수 있는 부분 진행하겠습니다.
- 사실 ViewModel에 DataSource를 넣고 싶었는데..guard let 구문 들때문에 View에서 구현하였습니다..
- UI는 일단 간략하게 구성했는데 수정 사항 같이 이야기 나눠보면 좋을 것 같습니다.
- 실행시 디자인 크리에이터만 보이는 이유는 필터 걸어서 [creator] 배열에 요소가 없으면 보이지 않게끔 구현해서 그렇습니다.
=> [FEATURE] ExploreView, ExploreViewModel 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Coordinator/ExploreCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/MainTabBarCoordinator.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/ExploreTabBarController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/ExploreViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSearchScene/View/ExploreSearchViewController.swift, FanFollow/FanFollow/Source/Util/Extension/Bundle+Extension.swift
- ExploreCoordinator 구현
- ExploreCoordinator 구현
- 내부 메서드 호출할 경우 coordinator 주입 처리
- ExploreView(메인)의 경우 ExploreTabBar에 Coordinator를 지정 후, ExploreView에게 Coordinator을 전달하는 방식을 사용했습니다.
=> [FEATURE] ExploreCoordinator 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorInformationUseCase.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/ExploreTapItem.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/View/ExploreSubscribeViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/ViewModel/ExploreSubscribeViewModel.swift, FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
- Explore 탭 내부 나의 구독 탭 구현
- ExploreSubscribeView, ViewModel 구현
- ExploreSubscribeView 구현
- ExploreSubscribeViewModel 구현
- FetchCreatorInformationUseCase 내부 특정 UserID의 팔로잉(구독한 크리에이터) 정보를 가져오는 fetchFollowings 메서드 추가
|기능|스크린샷|
|:---:|:---:|
|나의 구독|<img width = "300px" img src= "https://github.com/Young-Child/FanFollow/assets/59204352/ba736748-85dc-43ad-a2c7-d9ad0083367c">|
- 스크린샷은 페이지네이션 보여드리기 위해 pageCount 조작한 것입니다.
=> [FEATURE]/ExploreSubscribeView, ViewModel 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Application/SceneDelegate.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/ProfileImagePickerCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/ProfileSettingCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift, FanFollow/FanFollow/Source/Domain/Model/SettingSectionItem.swift, FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift, FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileImagePickerViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileSettingViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/SettingViewController.swift, FanFollow/FanFollow/Source/Util/Extension/Bundle+Extension.swift
- Setting 화면에서 하위 화면에 대한 전환 Coordinator 생성
- Setting Section Item
- Setting Coordinator
- Profile Setting Coordinator
=> [FEATURE] Setting 화면에 대한 Coordinator 설정

FanFollow/FanFollow/Source/Coordinator/SettingCoodinator.swift, FanFollow/FanFollow/Source/Domain/Model/Post.swift, FanFollow/FanFollow/Source/Domain/UseCase/UpdateProfileImageUseCase.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorCell.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorListCell.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSearchScene/View/ExploreSearchViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/View/ExploreSubscribeViewController.swift, FanFollow/FanFollow/Source/Presenter/FeedManageScene/View/CreatorInformationCell.swift, FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileImagePickerViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileSettingViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/ProfileSettingViewModel.swift, FanFollow/FanFollow/Source/Util/Extension/UI/UIImageView + Extension.swift
- Kingfisher 관련 메서드 변화로 인한 캐싱 버그 수정
사용자 프로필 설정 이미지 캐싱 키 적용
PostImage에 대한 캐싱 정책에 따른 메서드 변화
=> [BUG] Image 설정 메서드 변경으로 인한 버그 수정

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Coordinator/FeedCoordinator.swift, FanFollow/FanFollow/Source/Domain/UseCase/UploadPostUseCase.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/LinkUploadScene/UploadLinkViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/PhotoUploadScene/UploadPhotoViewController.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewModel/UploadViewModel.swift, FanFollow/UseCaseTests/ExploreUseCaseTests.swift, FanFollow/UseCaseTests/SearchCreatorUseCaseTests.swift, FanFollow/UseCaseTests/Stub/StubImageRepository.swift, FanFollow/UseCaseTests/UploadPostUseCaseTest.swift
- UploadPostUseCase Test 코드 작성
- Recovery Folder에 Upload가 있길래 폴더랑 삭제했습니다.
- UploadPostUseCase 내부 메서드 분리
- UploadPostUseCase Test 코드 작성
- Feed에서 다른 Tab 갔다가 다시 돌아올 경우 탭없어지는 오류 수정
|기능|스크린샷|
|:---:|:---:|
|Coverage|<img width="1288" alt="스크린샷 2023-08-06 오후 2 53 03" src="https://github.com/Young-Child/FanFollow/assets/59204352/89f3a48a-d650-4962-badc-b443f92ca136">|
- Explore Tab 원래 다른 Creator Profile로 잘 이동했었는데 갑자기 동작이 조금 이상하네요..
=> [TEST] UploadPostUseCase

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/UseCaseTests/AppleSigningUseCaseTests.swift, FanFollow/UseCaseTests/Stub/StubAuthRepository.swift
- AppleSigningUseCase Test Code 작성
- AppleSigningUseCase 내부 LogIn()메서드에 대한 Test Code 작성
- StubAuthRepository 구현
- 메서드가 1개라 별도의 사진은 첨부하지 않았습니다.
=> [TEST] AppleSigningUseCase Test Code 작성

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Resource/Assets.xcassets/AlertColor.colorset/Contents.json, FanFollow/FanFollow/Source/Coordinator/SettingScene/LogOutCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/WithdrawalCoordinator.swift, FanFollow/FanFollow/Source/Data/Repository/DefaultAuthRepository.swift, FanFollow/FanFollow/Source/Domain/Model/SettingSectionItem.swift, FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/AuthRepository.swift, FanFollow/FanFollow/Source/Domain/UseCase/LogOutUseCase.swift, FanFollow/FanFollow/Source/Domain/UseCase/WithdrawalUseCase.swift, FanFollow/FanFollow/Source/Network/Builder/AuthRequestDirector.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/UploadBottomSheetView.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewController/UploadBottomSheetViewController/UploadBottomSheetViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/LogOutWithdrawalScene/View/LogOutAlertView.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/LogOutWithdrawalScene/View/LogOutViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/LogOutWithdrawalScene/View/WithdrawalBottomSheetView.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/LogOutWithdrawalScene/View/WithdrawalViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/LogOutWithdrawalScene/ViewModel/LogOutViewModel.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/LogOutWithdrawalScene/ViewModel/WithdrawalViewModel.swift, FanFollow/UseCaseTests/Stub/StubAuthRepository.swift
- LogOut, Withdrawal(탈퇴) 기능 추가
- LogOutViewController, ViewModel 구현
- WithdrawalViewController, ViewModel 구현
- LogOutUseCase, WithdrawalUseCase 구현
- AuthRepository에 deleteUserID() 메서드 추가
- 기능의 화면이 변경되었다면, 사진을 남겨주세요.
- 없다면, 지우셔도 됩니다.
|기능|스크린샷|
|:---:|:---:|
|탈퇴|<img width = "300px" img src= "https://github.com/Young-Child/FanFollow/assets/59204352/ebe655f3-4d4d-4f4c-bb9a-214b61f3531e">|
|로그아웃|<img width = "300px" img src= "https://github.com/Young-Child/FanFollow/assets/59204352/55db4a84-e389-43ca-9c35-e650159535ea">|
- LogoutTest 예정
- WithdrawalTest 예정
=> [FEATURE] LogOut, Withdrawal 기능 추가

FanFollow/FanFollow/Source/Coordinator/ExploreScene/ProfileFeedCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/FeedScene/FeedCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/MailCoordinator.swift, FanFollow/FanFollow/Source/Presenter/Common/UI/View/NavigationBar.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/Controllers/ProfileFeedViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/ViewModel/ProfileFeedViewModel.swift, FanFollow/FanFollow/Source/Util/Constants/Constants.swift
- 사용자 신고 기능 추가
- Mail Coordinator 부분 수정
- FeedMangeViewController 및 ViewModel
- 사용자 신고 관련 메서드
=> [FEATURE] 사용자 신고 기능

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Coordinator/LogInScene/LogInCoordinator.swift, FanFollow/FanFollow/Source/Data/Service/DefaultNetworkService.swift, FanFollow/FanFollow/Source/Domain/Model/Setting/CreatorApplicationStep.swift, FanFollow/FanFollow/Source/Network/Directors/UserRequestDirector.swift, FanFollow/FanFollow/Source/Presenter/Common/UI/View/LinkableLabel.swift, FanFollow/FanFollow/Source/Presenter/LogInScene/Controllers/LogInViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/CreatorApplicationView/Controllers/ChildControllers/CreatorAgreementViewController.swift, FanFollow/FanFollow/Source/Util/Constants/Constants.swift
- 개인 정보 처리 방침과 앱 이용 약관을 로그인 화면에서 볼 수 있도록 변경
- 크리에이터 신청 시 안내 사항으로 변경
=> [FEATURE] App privacy 안내 사항 로그인에 추가

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Data/Repository/DefaultBlockContentRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/BlockContentRepository.swift, FanFollow/FanFollow/Source/Domain/UseCase/Post/BlockContentUseCase.swift, FanFollow/FanFollow/Source/Network/Directors/BlockContentRequestDirector.swift
- Content 숨기는 로직(Repository, UseCase, Director) 구현
- BlockContentRequestDirector 구현
- BlockContentRepository 구현
- BlockContentUseCase 구현
- 추후 테스트 예정
=> [FEATURE] Content Block 기능 관련 Director, Repository, UseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Data/Repository/DefaultAuthRepository.swift, FanFollow/FanFollow/Source/Data/Repository/DefaultReportRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/AuthRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/FollowRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/LikeRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/PostRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/ReportRepository.swift, FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift, FanFollow/FanFollow/Source/Domain/UseCase/Auth/SignUpUserUseCase.swift, FanFollow/FanFollow/Source/Domain/UseCase/Post/FetchFeedUseCase.swift, FanFollow/FanFollow/Source/Domain/UseCase/User/SendReportUseCase.swift, FanFollow/FanFollow/Source/Network/Directors/LikeRequestDirector.swift, FanFollow/FanFollow/Source/Network/Directors/PostRequestDirector.swift, FanFollow/FanFollow/Source/Network/Directors/ReportRequestDirector.swift, FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeView/ViewModel/ExploreSubscribeViewModel.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/UploadPostView/Controllers/UploadLinkViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/UploadPostView/Controllers/UploadPhotoViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/UploadPostView/View/UploadImageCell.swift, FanFollow/FanFollow/Source/Util/Extension/Notification + Extension.swift, FanFollow/RepositoryTests/AuthRepositoryTests.swift, FanFollow/RepositoryTests/FollowRepositoryTests.swift, FanFollow/RepositoryTests/Stub/StubNetworkService.swift, FanFollow/UseCaseTests/ApplyCreatorUseCaseTests.swift, FanFollow/UseCaseTests/ChangeLikeUseCaseTests.swift, FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift, FanFollow/UseCaseTests/FetchCreatorPostsUseCaseTests.swift, FanFollow/UseCaseTests/FetchFeedUseCaseTests.swift, FanFollow/UseCaseTests/FetchUserInformationUseCaseTests.swift, FanFollow/UseCaseTests/SignUpUserUseCaseTests.swift
- 신고 관련 Director, Repository, UseCase 구현
- ReportRequestDirector 구현
- ReportRepository 구현
- SendReportUseCase 구현
=> [FEATURE] 신고 관련 Director, Repository, UseCase 구현

FanFollow/FanFollow.xcodeproj/project.pbxproj, FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/BlockCreatorManagementCoordinator.swift, FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/CreatorApplicationCoordinator.swift, FanFollow/FanFollow/Source/Domain/Model/Setting/BlockCreator.swift, FanFollow/FanFollow/Source/Domain/Model/Setting/BlockCreatorSectionModel.swift, FanFollow/FanFollow/Source/Domain/Model/Setting/SettingSectionItem.swift, FanFollow/FanFollow/Source/Domain/Model/Setting/SettingSectionModel.swift, FanFollow/FanFollow/Source/Domain/UseCase/User/ManageBlockCreatorUseCase.swift, FanFollow/FanFollow/Source/Network/Directors/BlockUserDirector.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/BlockCreatorManagementView/Controllers/BlockCreatorManagementViewController.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/BlockCreatorManagementView/View/BlockCreatorCell.swift, FanFollow/FanFollow/Source/Presenter/SettingScene/BlockCreatorManagementView/ViewModel/BlockCreatorManagementViewModel.swift, FanFollow/FanFollow/Source/Util/Constants/Constants.swift
- 차단 사용자 관리 화면 구현
- BlockCreator 구현
- BlockCreatorSectionModel 구현
- BlockCreatorManagementViewModel 구현
- BlockCreatorManagementViewController 구현
- BlockCreatorCell 구현
|기능|스크린샷|
|:---:|:---:|
|차단 사용자 관리|![Simulator Screen Recording - iPhone 14 Pro - 2023-08-31 at 22 02 31](https://github.com/Young-Child/FanFollow/assets/48776496/9e06f57e-710f-4b42-88b3-f6ea90531554)|
=> [FEATURE] 차단 사용자 관리 화면 구현
